LTO_ENABLE = yes
VIA_ENABLE = yes
VIAL_ENABLE = yes
OLED_ENABLE = no
MOUSEKEY_ENABLE = no
EXTRAKEY_ENABLE = no
WPM_ENABLE = no
TAP_DANCE_ENABLE = yes
COMBO_ENABLE = yes
GRAVE_ESC_ENABLE = no
MAGIC_ENABLE = no
BOOTMAGIC_ENABLE = no

COMMAND_ENABLE = yes
CONSOLE_ENABLE = no

QMK_SETTINGS = yes

KEY_OVERRIDE_ENABLE = no
MUSIC_ENABLE = no